### PR TITLE
Use bootstrap classes to style tables by default

### PR DESCRIPTION
**Pull request by mgorny**
Signed-off-by: Michał Górny <mgorny@gentoo.org>

### CODE REVIEW

**Comment by mgorny** [comment]
CC @ulm, @thesamesam, @akhuettel, @SoapGentoo

**Comment by mgorny** [comment]
Before:
before

After:
after

**Review by SoapGentoo — APPROVED** [review]

**Review by thesamesam — APPROVED** [review]
Sooo much better!

**Comment by ulm** [comment]
Can we do without the zebra stripes please? See for example https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0001IV for a (lengthy) discussion.

tl;dr "... the alternating backgrounds are creating two distinct layers of focus in the tables when there is no difference between the alternating rows of information. The technique has value in instances where there is a distinction you want to make visible, but used in a simple list, it confuses the eye into thinking there are two separate types of information."

**Comment by mgorny** [comment]
Unfortunately, bootstrap insists on stretching the table to the full width, and that makes it very hard to read on wide screens, especially if one has eye dysfunction.

**Comment by ulm** [comment]
> Unfortunately, bootstrap insists on stretching the tabe to the full width, and that makes it very hard to read on wide screens, especially if one has eye dysfunction.

Can't we throw in a `style="width: auto;"` to avoid this? I guess full width is acceptable for the table in GLEP 74, but I'd imagine that it would be ugly for a table with two or three narrow columns.

**Comment by mgorny** [comment]
Managed that. That's how it looks now:

after2

I think I'd personally prefer some more padding inside but that's just me.

**Comment by mgorny** [comment]
I've also added `vertical-align: middle` for table cells to make `rowspan`s useful.

Hash algos without rowspan:
c1

with rowspan:
c2

**Review by SoapGentoo — APPROVED** [review]

**Review by ulm — APPROVED** [review]

**Review by thesamesam — APPROVED** [review]

**Comment by thesamesam** [comment]
(FWIW, I prefer the rowspan variant)

**Pull request closed without merging**
